### PR TITLE
Single md with pandoc

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
can you solve the conflicts and compare the md generated with pandoc with mine? still i think that having my linter and a shellscript implementation to verify links is good, so it helps having some consistency on the changes

**Comment by trufae** [comment]
@prodrigestivill

**Comment by prodrigestivill** [comment]
I will wait until the new lint format validation is merged (#388) or discarted before starting this.

**Comment by prodrigestivill** [comment]
Closing for now, will reopen if the investigation succeeds.

**Pull request closed without merging**
