### PR TITLE
Prefix 'e when setting multiple symbol servers

### PR DESCRIPTION
**Pull request by davispuh**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

Prefix 'e when setting multiple symbol servers

### CODE REVIEW

**Comment by trufae** [comment]
Personally i think we should use space or comma as separator token instead. The single quote char is a general way to avoid evaluating special characters but you can also use backslash or double quote “ the whole thing. But probably i would prefer to change the code in r2 rather than documenting something that is probably not intuitive

**Comment by davispuh** [comment]
Yeah that would be better. As it is currently `"` quotes (nor `\;`) doesn't work either because it interprets it as part of URL...

I think space as separator would make most sense (for actual space in URL you can just use `%20`) and supporting quotes could be alternate way for `'`

**Comment by trufae** [comment]
here we go! https://github.com/radareorg/radare2/pull/22636

thanks !

**Comment by trufae** [comment]
feel free to check the documentation in case its still referencing semicolon somewhere. i think the semicolon syntax comes from the awful windows env separator thing.

**Comment by davispuh** [comment]
Nice! I updated it in #371

**Pull request closed without merging**
